name: 'Build and Deploy to GKE'

on:
  push:
    branches:
      - 'main'

env:
  DEPLOYMENT_NAME: 'pr-analytics' 
  REPOSITORY: 'gcr.io'
  IMAGE: 'pr-analytics'
  PROJECT_ID: 'nonprod1-svc-r4rc'
  GAR_LOCATION: 'us-central1'
  GKE_CLUSTER: 'pipeline-cluster-1'
  GKE_LOCATION: 'us-central1'
  WORKLOAD_IDENTITY_PROVIDER: 'projects/913084804953/locations/global/workloadIdentityPools/github/providers/github'
  SERVICE_ACCOUNT_EMAIL: 'github-actions@nonprod1-svc-r4rc.iam.gserviceaccount.com'


jobs:
  setup-build-publish-deploy:
    name: 'Setup, Build, Publish, and Deploy'
    runs-on: 'ubuntu-latest'
    environment: 'dev'

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v4' 

      # Configure Workload Identity Federation and generate an access token.
      #
      # See https://github.com/google-github-actions/auth for more options,
      # including authenticating via a JSON credentials file.
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: '${{ env.WORKLOAD_IDENTITY_PROVIDER }}'
          service_account: "${{ env.SERVICE_ACCOUNT_EMAIL }}"
          project_id: "${{ env.PROJECT_ID }}"
          token_format: "access_token"

      # Authenticate Docker to Google Cloud Artifact Registry
      - name: Configure Docker to use GCR
        run: |
          gcloud auth configure-docker

      # Get the GKE credentials so we can deploy to the cluster
      - name: 'Set up GKE credentials'
        uses: 'google-github-actions/get-gke-credentials@v2'
        with:
          cluster_name: '${{ env.GKE_CLUSTER }}'
          location: '${{ env.GKE_LOCATION }}'

      # Build the Docker image
      - name: 'Build and push Docker container'
        run: |-
          DOCKER_TAG="${REPOSITORY}/${PROJECT_ID}/github.com/voicingai/${IMAGE}:${GITHUB_SHA}"
          docker build \
            --tag "${DOCKER_TAG}" \
            .

          docker push "${DOCKER_TAG}"

      # Install helm
      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

      # Deploy the Docker image to the GKE cluster
      - name: Deploy
        run: |
          helm upgrade --install $DEPLOYMENT_NAME helm-charts/ -f helm-charts/overrides/override-dev.yaml -n dev\
            --set image.tag=$GITHUB_SHA \
            --wait
          kubectl rollout status deployment/$DEPLOYMENT_NAME -n dev
          kubectl get services -o wide -n dev
      
